#version: '3.3'
#services:
#
#  frontend:
#    build:
#      context: ../frontend
#      dockerfile: Dockerfile
#    volumes:
#      - ../frontend/:/app/result_build/
#  nginx:
#    image: nginx:1.19.3
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - ../frontend/build:/usr/share/nginx/html/
#      - ../docs/:/usr/share/nginx/html/api/docs/

version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  frontend:
    image: norjunior/frontend:v1
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  backend:
    image: norjunior/backend:v1
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine

    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media_value:/var/html/media/

    depends_on:
      - backend

volumes:
  db_value:
  static_value:
  media_value:
