version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  frontend:
    image: norjunior/frontend:v1
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  backend:
    image: norjunior/backend:v1
    restart: always
    volumes:
      - static_value:/app/static_back/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "80:80"

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/var/html/static_back/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media_value:/var/html/media/

    depends_on:
      - backend

volumes:
  db_value:
  static_value:
  media_value:
